CREATE TABLE `consume_bill` (
  `id` bigint NOT NULL COMMENT '账单唯一ID',
  `cashs` json DEFAULT NULL COMMENT '现金支付明细数组',
  `cards` json DEFAULT NULL COMMENT '会员卡支付明细数组',
  `channel` varchar(50) DEFAULT NULL COMMENT '渠道',
  `jsonStr` text DEFAULT NULL COMMENT '业务扩展JSON字符串',
  `clientflag` varchar(10) DEFAULT NULL COMMENT '客户端标识',
  `feedbackComment` varchar(500) DEFAULT NULL COMMENT '反馈评论',
  `billtype` tinyint DEFAULT NULL COMMENT '账单类型',
  `eafee` varchar(30) DEFAULT NULL COMMENT '实收金额',
  `custId` bigint DEFAULT NULL COMMENT '客户ID',
  `lotteryStatus` tinyint DEFAULT NULL COMMENT '抽奖状态',
  `feedbackDT` datetime DEFAULT NULL COMMENT '反馈时间',
  `consumefee` varchar(20) DEFAULT NULL COMMENT '消费总金额',
  `consumeshopname` varchar(100) DEFAULT NULL COMMENT '消费门店名称',
  `consumeType` tinyint DEFAULT NULL COMMENT '消费类型',
  `mgjIsHighQualityCust` varchar(10) DEFAULT NULL COMMENT '是否优质客户',
  `createDate` bigint DEFAULT NULL COMMENT '账单创建时间戳',
  `memberId` bigint DEFAULT NULL COMMENT '会员ID',
  `remainFee` varchar(20) DEFAULT NULL COMMENT '剩余金额',
  `addOverallScore` int DEFAULT NULL COMMENT '新增积分',
  `billstatus` tinyint DEFAULT NULL COMMENT '账单状态',
  `debtBillId` varchar(50) DEFAULT NULL COMMENT '欠款账单ID',
  `expenseCategory` tinyint DEFAULT NULL COMMENT '消费分类',
  `overallScore` int DEFAULT NULL COMMENT '总积分',
  `sex` char(2) DEFAULT NULL COMMENT '性别 M-男 F-女',
  `cardType` tinyint DEFAULT NULL COMMENT '会员卡类型',
  `settlementChannel` varchar(50) DEFAULT NULL COMMENT '结算渠道',
  `expense` varchar(20) DEFAULT NULL COMMENT '消费金额',
  `storeId` bigint DEFAULT NULL COMMENT '门店ID',
  `lotteryType` tinyint DEFAULT NULL COMMENT '抽奖类型',
  `otherflag` tinyint DEFAULT NULL COMMENT '其他标志',
  `name` varchar(50) DEFAULT NULL COMMENT '顾客名称',
  `comment` varchar(500) DEFAULT NULL COMMENT '备注',
  `addFeedbackComment` varchar(500) DEFAULT NULL COMMENT '追加评论',
  `auditingFlag` tinyint DEFAULT NULL COMMENT '审核标志',
  `items` json DEFAULT NULL COMMENT '消费项目明细数组',
  `billno` varchar(30) DEFAULT NULL COMMENT '账单编号',
  `freezeType` tinyint DEFAULT NULL COMMENT '冻结类型',
  `billingChannel` varchar(50) DEFAULT NULL COMMENT '记账渠道',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费账单表（1:1匹配JSON）';