[
  {
    authStdModule: {
      id: 2,
      groupId: 0,
      moduleGroupKey: 'DashRouter',
      moduleKey: 'DashRouter',
      displaySn: 1,
      moduleName: '概览',
      devName: '概览',
      menuModeIcon: 'el-icon-s-help',
      logicalDelete: 0,
      remark: '数据概览',
    },
    authStdFuncList: [
      {
        id: 6,
        funcKey: 'E_Data_View_Func_View',
        moduleId: 2,
        funcName: '查看概览数据',
        displaySn: 0,
        toolTip: '查看概览数据',
        devName: '概览',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 4,
      groupId: 0,
      moduleGroupKey: 'BedStatus',
      moduleKey: 'BedStatus',
      displaySn: 1,
      moduleName: '房态',
      devName: '房态',
      menuModeIcon: 'el-icon-s-grid',
      logicalDelete: 0,
      remark: '房态',
    },
    authStdFuncList: [
      {
        id: 117,
        funcKey: 'E_RoomState_NewBill',
        moduleId: 4,
        funcName: '开单操作(含新增明细)',
        displaySn: 1,
        toolTip: '在房态功能中的开单操作权限(门店)',
        devName: '房态',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 119,
        funcKey: 'E_RoomState_StartEnd_Service',
        moduleId: 4,
        funcName: '上下钟操作',
        displaySn: 2,
        toolTip: '在房态功能中的技师上下钟操作权限(门店)',
        devName: '房态',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 121,
        funcKey: 'E_RoomState_BillDetail_Modify',
        moduleId: 4,
        funcName: '修改单据明细操作(含取消账单)',
        displaySn: 3,
        toolTip: '在房态功能中的修改单据明细(含取消账单)的操作权限(门店)',
        devName: '房态',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 6,
      groupId: 0,
      moduleGroupKey: 'SaleMain',
      moduleKey: 'SaleMain',
      displaySn: 1,
      moduleName: '收银',
      devName: '收银',
      menuModeIcon: 'el-icon-s-platform',
      logicalDelete: 0,
      remark: '收银',
    },
    authStdFuncList: [
      {
        id: 123,
        funcKey: 'E_Cash_NewBill',
        moduleId: 6,
        funcName: '开单(含明细修改)操作',
        displaySn: 1,
        toolTip: '在收银功能中的开单(含明细修改)的操作权限(门店)',
        devName: '收银',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 125,
        funcKey: 'E_Cash_Settlement',
        moduleId: 6,
        funcName: '结算操作',
        displaySn: 2,
        toolTip: '在收银功能中的结算的操作权限(门店)',
        devName: '收银',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 128,
        funcKey: 'E_Cash_CustomPrice',
        moduleId: 6,
        funcName: '自定义单价',
        displaySn: 3,
        toolTip: '在收银功能中自定义单价的操作权限(门店)',
        devName: '收银',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 129,
        funcKey: 'E_Cash_Discount',
        moduleId: 6,
        funcName: '整单打折操作',
        displaySn: 4,
        toolTip: '在收银功能中的整单打折的操作权限(门店)',
        devName: '收银',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 131,
        funcKey: 'E_Cash_Cancel_Bill',
        moduleId: 6,
        funcName: '取消订单操作',
        displaySn: 5,
        toolTip: '在收银功能中的取消订单的操作权限(门店)',
        devName: '收银',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 132,
        funcKey: 'E_Use_Entity_Coupon',
        moduleId: 6,
        funcName: '是否可以使用实体券结算',
        displaySn: 7,
        toolTip: '在收银功能中的结算是否可以使用实体券',
        devName: '收银',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 7,
      groupId: 0,
      moduleGroupKey: 'StaffMain',
      moduleKey: 'StaffMain',
      displaySn: 1,
      moduleName: '人事',
      devName: '人事',
      menuModeIcon: 'el-icon-s-custom',
      logicalDelete: 0,
      remark: '人事管理',
    },
    authStdFuncList: [
      {
        id: 7,
        funcKey: 'E_HR_Staff_Add',
        moduleId: 7,
        funcName: '人员资料新增',
        displaySn: 1,
        toolTip: '新增员工操作权限',
        devName: '人事-员工资料',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 9,
        funcKey: 'E_HR_Staff_Modify',
        moduleId: 7,
        funcName: '人员资料修改',
        displaySn: 2,
        toolTip: '修改员工操作权限',
        devName: '人事-员工资料',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 15,
        funcKey: 'E_HR_Staff_Skill_Modify',
        moduleId: 7,
        funcName: '技师技能修改',
        displaySn: 5,
        toolTip: '修改员工所具有的职业技能的权限',
        devName: '人事-技师管理',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
        remark: '',
      },
      {
        id: 17,
        funcKey: 'E_HR_Staff_Auth_Modify',
        moduleId: 7,
        funcName: '人员系统权限修改',
        displaySn: 6,
        toolTip: '修改员工的系统操作的权限',
        devName: '人事-员工权限',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 8,
      groupId: 1,
      moduleGroupKey: 'MemGroup',
      moduleKey: 'MemMain',
      displaySn: 1,
      moduleName: '电子会员卡',
      devName: '会员',
      menuModeIcon: 'el-icon-s-marketing',
      logicalDelete: 0,
      remark: '会员-- 电子会员卡',
    },
    authStdFuncList: [
      {
        id: 21,
        funcKey: 'E_Mem_Data_Add',
        moduleId: 8,
        funcName: '会员资料新增',
        displaySn: 1,
        toolTip: '新增会员资料的权限',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 23,
        funcKey: 'E_Mem_Data_Modify',
        moduleId: 8,
        funcName: '会员资料修改',
        displaySn: 2,
        toolTip: '修改会员资料的权限',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 25,
        funcKey: 'E_Mem_Data_TelNo_View',
        moduleId: 8,
        funcName: '会员电话号码查看',
        displaySn: 3,
        toolTip: '查看会员电话号码的权限',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
        remark: '所有涉及电话显示的地方，但不包含修改',
      },
      {
        id: 31,
        funcKey: 'E_Mem_Data_Export',
        moduleId: 8,
        funcName: '会员资料的导出',
        displaySn: 6,
        toolTip: '导出会员资料到Excel文件的操作权限',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1001111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
        remark: '',
      },
      {
        id: 148,
        funcKey: 'E_Mem_Data_Reset_Pwd',
        moduleId: 8,
        funcName: '会员密码重置',
        displaySn: 7,
        toolTip: '重置会员密码的操作权限',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 172,
        funcKey: 'E_Mem_Statistics_View',
        moduleId: 8,
        funcName: '导出会员资产表以及查看门店负债',
        displaySn: 8,
        toolTip: '导出会员资产表以及查看门店负债的权限',
        devName: '电子会员卡-会员统计',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 174,
        funcKey: 'E_Mem_Old_Data_View',
        moduleId: 8,
        funcName: '老系统会员数据查看(消费/充值/期末余额)',
        displaySn: 9,
        toolTip: '老系统会员数据查看(消费/充值/期末余额)的权限',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
        remark: '',
      },
      {
        id: 176,
        funcKey: 'E_Mem_Fin_Cross_Modify',
        moduleId: 8,
        funcName: '是否允许修改会员资产可跨店',
        displaySn: 10,
        toolTip: '是否允许修改会员资产可跨店',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
        remark: '',
      },
      {
        id: 178,
        funcKey: 'E_Mem_Get_Conpon_Offine',
        moduleId: 8,
        funcName: '允许直接赠送/取消会员优惠券',
        displaySn: 11,
        toolTip: '允许直接赠送/取消会员优惠券',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
        remark: '',
      },
      {
        id: 179,
        funcKey: 'E_Mem_Gift_Recharge_Send',
        moduleId: 8,
        funcName: '赠送会员卡金',
        displaySn: 12,
        toolTip: '赠送会员卡金',
        devName: '电子会员卡-会员列表',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 184,
        funcKey: 'E_Trans_Mem_Fins',
        moduleId: 8,
        funcName: '转移会员资产',
        displaySn: 12,
        toolTip: '转移会员资产',
        devName: '电子会员卡-转移会员资产',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 10,
      groupId: 1,
      moduleGroupKey: 'MemGroup',
      moduleKey: 'RechMain',
      displaySn: 2,
      moduleName: '会员卡充值',
      devName: '会员',
      menuModeIcon: 'el-icon-s-marketing',
      logicalDelete: 0,
      remark: '会员-- 会员卡充值',
    },
    authStdFuncList: [
      {
        id: 35,
        funcKey: 'E_Mem_Recharge',
        moduleId: 10,
        funcName: '会员卡充值操作',
        displaySn: 1,
        toolTip: '给会员卡充值的操作权限(门店)',
        devName: '会员卡充值-会员充值',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 37,
        funcKey: 'E_Mem_Recharge_Record_View',
        moduleId: 10,
        funcName: '会员卡充值记录的查询',
        displaySn: 2,
        toolTip: '查询会员卡充值记录的操作权限',
        devName: '会员卡充值-充值记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 41,
        funcKey: 'E_Mem_Recharge_Promotion_Add',
        moduleId: 10,
        funcName: '会员卡充值活动的新增',
        displaySn: 4,
        toolTip: '新增会员卡充值活动的操作权限(门店)',
        devName: '会员卡充值-充值活动',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 43,
        funcKey: 'E_Mem_Recharge_Promotion_Ctrl',
        moduleId: 10,
        funcName: '会员卡充值活动的启用/禁用',
        displaySn: 5,
        toolTip: '会员卡充值活动的启用和禁用的操作权限(门店)',
        devName: '会员卡充值-充值活动',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 146,
        funcKey: 'E_Mem_Recharge_Refund',
        moduleId: 10,
        funcName: '会员卡充值冲正',
        displaySn: 6,
        toolTip:
          '会员卡充值冲正的操作权限(要勾选本权限【会员卡充值记录的查询】必须选择)',
        devName: '会员卡充值-充值记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 170,
        funcKey: 'E_Mem_Recharge_Discount_Modify',
        moduleId: 10,
        funcName: '充值时折扣率及折扣基础允许修改',
        displaySn: 7,
        toolTip: '充值时允许操作员手动修改折扣率及折扣基础',
        devName: '会员卡充值-会员充值',
        orgFuncType: 1111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 11,
      groupId: 1,
      moduleGroupKey: 'MemGroup',
      moduleKey: 'CouponMain',
      displaySn: 3,
      moduleName: '会员优惠券',
      devName: '会员',
      menuModeIcon: 'el-icon-s-marketing',
      logicalDelete: 0,
      remark: '会员-- 会员优惠券',
    },
    authStdFuncList: [
      {
        id: 47,
        funcKey: 'E_Coupon_Add',
        moduleId: 11,
        funcName: '会员优惠券的新增',
        displaySn: 1,
        toolTip: '新增会员优惠券的操作权限(门店)',
        devName: '会员优惠券-优惠券管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 49,
        funcKey: 'E_Coupon_Ctrl',
        moduleId: 11,
        funcName: '会员优惠券的启用/禁用',
        displaySn: 2,
        toolTip: '会员优惠券的启用和禁用的操作权限(门店)',
        devName: '会员优惠券-优惠券管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 160,
        funcKey: 'E_Coupon_GroundPromotion_Set',
        moduleId: 11,
        funcName: '地推活动的设置',
        displaySn: 3,
        toolTip: '地推活动的设置(门店)',
        devName: '会员优惠券-地推活动',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 203,
        funcKey: 'E_Coupon_Delay_Limit',
        moduleId: 11,
        funcName: '会员失效优惠券延期',
        displaySn: 3,
        toolTip: '会员失效优惠券延期',
        devName: '会员优惠券-地推活动',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 12,
      groupId: 2,
      moduleGroupKey: 'OrgGroup',
      moduleKey: 'OrgMgr',
      displaySn: 1,
      moduleName: '门店管理',
      devName: '门店',
      menuModeIcon: 'el-icon-s-home',
      logicalDelete: 0,
      remark: '门店-- 门店管理',
    },
    authStdFuncList: [
      {
        id: 55,
        funcKey: 'E_Org_Data_Modify',
        moduleId: 12,
        funcName: '门店或管理机构的资料修改',
        displaySn: 2,
        toolTip: '门店或管理机构的资料修改权限',
        devName: '门店管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 14,
      groupId: 2,
      moduleGroupKey: 'OrgGroup',
      moduleKey: 'UnionMgr',
      displaySn: 2,
      moduleName: '联盟管理',
      devName: '门店',
      menuModeIcon: 'el-icon-s-home',
      logicalDelete: 0,
      remark: '门店-- 联盟管理',
    },
    authStdFuncList: [
      {
        id: 166,
        funcKey: 'E_Union_List_Show',
        moduleId: 14,
        funcName: '查看门店所属联盟',
        displaySn: 4,
        toolTip: '查看门店所属联盟',
        devName: '联盟管理',
        orgFuncType: 111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 16,
      groupId: 3,
      moduleGroupKey: 'DataGroup',
      moduleKey: 'SaleData',
      displaySn: 1,
      moduleName: '销售数据',
      devName: '数据',
      menuModeIcon: 'el-icon-s-data',
      logicalDelete: 0,
      remark: '数据-- 门店销售',
    },
    authStdFuncList: [
      {
        id: 144,
        funcKey: 'E_Sales_Refund',
        moduleId: 16,
        funcName: '销售冲正',
        displaySn: 7,
        toolTip: '销售数据的冲正操作权限',
        devName: '销售数据-销售记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 164,
        funcKey: 'E_Sales_Record_PayWay_Modify',
        moduleId: 16,
        funcName: '销售记录中支付方式修改',
        displaySn: 8,
        toolTip: '销售记录中支付方式修改操作权限',
        devName: '销售数据-销售记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 168,
        funcKey: 'E_Sales_Record_Staff_Modify',
        moduleId: 16,
        funcName: '销售记录中技师修改',
        displaySn: 9,
        toolTip: '销售记录中技师修改操作权限【本功能暂时未完成】',
        devName: '销售数据-销售记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 20,
      groupId: 3,
      moduleGroupKey: 'DataGroup',
      moduleKey: 'StaffPerf',
      displaySn: 2,
      moduleName: '人员绩效',
      devName: '数据',
      menuModeIcon: 'el-icon-s-data',
      logicalDelete: 0,
      remark: '数据-- 人员绩效',
    },
    authStdFuncList: [
      {
        id: 77,
        funcKey: 'E_Perf_View',
        moduleId: 20,
        funcName: '技师绩效的查询',
        displaySn: 1,
        toolTip: '技师绩效的查询操作权限',
        devName: '技师绩效-业绩明细',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 79,
        funcKey: 'E_Perf_Export',
        moduleId: 20,
        funcName: '技师绩效的导出',
        displaySn: 2,
        toolTip: '技师绩效导出到Excel文件的的操作权限(导出后可汇总)',
        devName: '技师绩效-业绩明细',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 139,
        funcKey: 'E_Perf_Total_View',
        moduleId: 20,
        funcName: '业绩汇总的查询',
        displaySn: 3,
        toolTip: '业绩汇总的查询操作权限',
        devName: '技师绩效-业绩汇总',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 141,
        funcKey: 'E_Perf_Total_Export',
        moduleId: 20,
        funcName: '业绩汇总的导出',
        displaySn: 4,
        toolTip: '业绩汇总导出到Excel文件的的操作权限(导出后可汇总)',
        devName: '技师绩效-业绩汇总',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 21,
      groupId: 4,
      moduleGroupKey: 'SetGroup',
      moduleKey: 'PSMain',
      displaySn: 1,
      moduleName: '品项设定',
      devName: '设定',
      menuModeIcon: 'el-icon-s-tools',
      logicalDelete: 0,
      remark: '设定-- 品项设定',
    },
    authStdFuncList: [
      {
        id: 83,
        funcKey: 'E_ProductItem_Product_Add',
        moduleId: 21,
        funcName: '产品的新增',
        displaySn: 1,
        toolTip: '新增销售产品(非服务)的操作权限(门店)',
        devName: '品项设定-产品管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 85,
        funcKey: 'E_ProductItem_Product_Modify',
        moduleId: 21,
        funcName: '产品的修改',
        displaySn: 2,
        toolTip: '修改销售产品(非服务)的操作权限(门店)',
        devName: '品项设定-产品管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 87,
        funcKey: 'E_ProductItem_Product_Ctrl',
        moduleId: 21,
        funcName: '产品的启用/禁用',
        displaySn: 3,
        toolTip: '销售产品(非服务)的启用和禁用操作的权限(门店)',
        devName: '品项设定-产品管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 89,
        funcKey: 'E_ProductItem_ServiceItem_Add',
        moduleId: 21,
        funcName: '服务项目的新增',
        displaySn: 4,
        toolTip: '新增服务项目的操作权限(门店)',
        devName: '品项设定-项目管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 91,
        funcKey: 'E_ProductItem_ServiceItem_Modify',
        moduleId: 21,
        funcName: '服务项目的修改',
        displaySn: 5,
        toolTip: '修改服务项目的操作权限(门店)',
        devName: '品项设定-项目管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 93,
        funcKey: 'E_ProductItem_ServiceItem_Ctrl',
        moduleId: 21,
        funcName: '服务项目的启用/禁用',
        displaySn: 6,
        toolTip: '服务项目的启用和禁用操作的权限(门店)',
        devName: '品项设定-项目管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 95,
        funcKey: 'E_ProductItem_Package_Add',
        moduleId: 21,
        funcName: '套餐的新增',
        displaySn: 7,
        toolTip: '新增套餐的操作权限(门店)',
        devName: '品项设定-套餐管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 97,
        funcKey: 'E_ProductItem_Package_Modify',
        moduleId: 21,
        funcName: '套餐的修改',
        displaySn: 8,
        toolTip: '修改套餐的操作权限(门店)',
        devName: '品项设定-套餐管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 99,
        funcKey: 'E_ProductItem_Package_Ctrl',
        moduleId: 21,
        funcName: '套餐的启用/禁用',
        displaySn: 9,
        toolTip: '套餐的启用和禁用操作的权限(门店)',
        devName: '品项设定-套餐管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 101,
        funcKey: 'E_ProductItem_Rechage_Percentages_Add',
        moduleId: 21,
        funcName: '充值提成规则的新增',
        displaySn: 10,
        toolTip: '新增充值提成规则的操作权限(门店)',
        devName: '品项设定-充值提成规则',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 103,
        funcKey: 'E_ProductItem_Rechage_Percentages_Modify',
        moduleId: 21,
        funcName: '充值提成规则的修改',
        displaySn: 11,
        toolTip: '修改充值提成规则的操作权限(门店)',
        devName: '品项设定-充值提成规则',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 105,
        funcKey: 'E_ProductItem_Rechage_Percentages_Ctrl',
        moduleId: 21,
        funcName: '充值提成规则的启用/禁用',
        displaySn: 12,
        toolTip: '充值提成规则的启用和禁用操作权限(门店)',
        devName: '品项设定-充值提成规则',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 198,
        funcKey: 'E_ProductItem_TreatmentItem_Add',
        moduleId: 21,
        funcName: '疗程券的新增',
        displaySn: 10,
        toolTip: '新增疗程券的操作权限(门店)',
        devName: '品项设定-疗程券管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 200,
        funcKey: 'E_ProductItem_TreatmentItem_Modify',
        moduleId: 21,
        funcName: '疗程券的修改',
        displaySn: 11,
        toolTip: '修改疗程券的操作权限(门店)',
        devName: '品项设定-疗程券管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 202,
        funcKey: 'E_ProductItem_TreatmentItem_Ctrl',
        moduleId: 21,
        funcName: '疗程券的启用/禁用',
        displaySn: 12,
        toolTip: '疗程券的启用和禁用操作的权限(门店)',
        devName: '品项设定-疗程券管理',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 22,
      groupId: 4,
      moduleGroupKey: 'SetGroup',
      moduleKey: 'RoomBed',
      displaySn: 2,
      moduleName: '房间设定',
      devName: '设定',
      menuModeIcon: 'el-icon-s-tools',
      logicalDelete: 0,
      remark: '设定-- 房间设定',
    },
    authStdFuncList: [
      {
        id: 109,
        funcKey: 'E_RoomBed_Set_Add',
        moduleId: 22,
        funcName: '房间/床位的新增',
        displaySn: 1,
        toolTip: '新增房间/床位的操作权限(门店)',
        devName: '房间设定',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 111,
        funcKey: 'E_RoomBed_Set_Modify',
        moduleId: 22,
        funcName: '房间/床位的修改',
        displaySn: 2,
        toolTip: '修改房间/床位的操作权限(门店)',
        devName: '房间设定',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 113,
        funcKey: 'E_RoomBed_Set_Delete',
        moduleId: 22,
        funcName: '房间/床位的删除',
        displaySn: 3,
        toolTip: '删除房间/床位的操作权限(门店)【本功能暂时未完成】',
        devName: '房间设定',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
      {
        id: 115,
        funcKey: 'E_RoomBed_Set_Ctrl',
        moduleId: 22,
        funcName: '房间/床位的暂停使用/恢复',
        displaySn: 4,
        toolTip: '房间/床位的暂停使用和恢复操作的权限(门店)',
        devName: '房间设定',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '1',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 23,
      groupId: 5,
      moduleGroupKey: 'SmsGroup',
      moduleKey: 'SmsRecharge',
      displaySn: 1,
      moduleName: '短信充值',
      devName: '短信',
      menuModeIcon: 'el-icon-chat-dot-square',
      logicalDelete: 0,
      remark: '短信-- 短信充值',
    },
    authStdFuncList: [
      {
        id: 186,
        funcKey: 'E_SMS_Recharge_Option',
        moduleId: 23,
        funcName: '短信充值操作',
        displaySn: 1,
        toolTip: '短信充值操作',
        devName: '短信-短信充值',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.2',
        logicalDelete: 0,
      },
      {
        id: 188,
        funcKey: 'E_SMS_Recharge_History',
        moduleId: 23,
        funcName: '短信充值历史查询',
        displaySn: 1,
        toolTip: '短信充值历史查询',
        devName: '短信-短信充值',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.2',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 24,
      groupId: 5,
      moduleGroupKey: 'SmsGroup',
      moduleKey: 'HistorySms',
      displaySn: 2,
      moduleName: '短信记录',
      devName: '短信',
      menuModeIcon: 'el-icon-chat-dot-square',
      logicalDelete: 0,
      remark: '短信-- 短信记录',
    },
    authStdFuncList: [
      {
        id: 190,
        funcKey: 'E_SMS_Notice_Send_History',
        moduleId: 24,
        funcName: '通知类短信查询和设置',
        displaySn: 2,
        toolTip: '通知类短信查询和设置',
        devName: '短信-查看短信记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.2',
        logicalDelete: 0,
      },
      {
        id: 192,
        funcKey: 'E_SMS_Market_Send_History',
        moduleId: 24,
        funcName: '营销短信查询和明细查看',
        displaySn: 2,
        toolTip: '营销短信查询和明细查看',
        devName: '短信-查看短信记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.2',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 25,
      groupId: 5,
      moduleGroupKey: 'SmsGroup',
      moduleKey: 'PushSms',
      displaySn: 3,
      moduleName: '短信营销',
      devName: '短信',
      menuModeIcon: 'el-icon-chat-dot-square',
      logicalDelete: 0,
      remark: '短信-- 短信营销',
    },
    authStdFuncList: [
      {
        id: 194,
        funcKey: 'E_SMS_Market_Edit_Send',
        moduleId: 25,
        funcName: '营销短信编辑和发送',
        displaySn: 2,
        toolTip: '营销短信编辑和发送',
        devName: '短信-短信营销',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.2',
        logicalDelete: 0,
      },
    ],
  },
  {
    authStdModule: {
      id: 27,
      groupId: 3,
      moduleGroupKey: 'DataGroup',
      moduleKey: 'PayData',
      displaySn: 3,
      moduleName: '支付数据',
      devName: '数据',
      menuModeIcon: 'el-icon-cteam-fufei',
      logicalDelete: 0,
      remark: '数据-- 支付数据',
    },
    authStdFuncList: [
      {
        id: 195,
        funcKey: 'E_Pay_Data_View',
        moduleId: 27,
        funcName: '线上支付数据查询',
        displaySn: 1,
        toolTip: '线上支付数据查询操作权限',
        devName: '支付数据-支付记录',
        orgFuncType: 1111111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.9',
        logicalDelete: 0,
      },
      {
        id: 196,
        funcKey: 'E_Pay_Refund',
        moduleId: 27,
        funcName: '支付业务单退款',
        displaySn: 1,
        toolTip: '线上支付退款权限',
        devName: '支付数据-退款操作',
        orgFuncType: 1001111,
        cliType: 1,
        isDefault: 1,
        miniVersion: '2.0.9',
        logicalDelete: 0,
      },
    ],
  },
];
